# Generated by Django 4.2.7 on 2025-10-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeldeployment',
            name='model',
        ),
        migrations.AlterUniqueTogether(
            name='modelfeedback',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='modelfeedback',
            name='inference_request',
        ),
        migrations.RemoveField(
            model_name='modelfeedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='modelusagelog',
            name='inference_request',
        ),
        migrations.RemoveField(
            model_name='modelusagelog',
            name='model',
        ),
        migrations.RemoveField(
            model_name='modelusagelog',
            name='user',
        ),
        migrations.DeleteModel(
            name='InferenceRequest',
        ),
        migrations.DeleteModel(
            name='ModelDeployment',
        ),
        migrations.DeleteModel(
            name='ModelFeedback',
        ),
        migrations.DeleteModel(
            name='ModelUsageLog',
        ),
    ]
